set(SRC_FILES
        src/App/App.cpp
        src/App/main.cpp
        src/Character/Player.cpp
        src/Map/Map.cpp
        src/Map/Stair.cpp
        src/Map/Door.cpp
        src/Item/Item.cpp
        src/System/CollisionHandler.cpp
        src/System/NPCDialog.cpp
        src/System/ShopScene.cpp
        src/System/ShopEventManager.cpp
        src/Shop/Shop.cpp
)

set(INCLUDE_FILES
        include/App/App.hpp
        include/Character/Player.hpp
        include/Character/Character.hpp
        include/Map/Map.hpp
        include/Map/Stair.hpp
        include/Map/Door.hpp
        include/Item/Item.hpp
        include/System/CollisionHandler.hpp
        include/System/NPCDialog.hpp
        include/System/ShopScene.hpp
        include/System/ShopEventManager.hpp
        include/Shop/Shop.hpp
)

set(TEST_FILES
)
